shiny:
  image:
    repository: jean-seb-2106/statconcepts
    tag: "1.0"
  ingress:
    enabled: true
    hostname: statconcepts.lab.sspcloud.fr
  s3:
    enabled: false
  postgresql:
    enabled: false